# Generated by Django 5.2.7 on 2024-10-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=100)),
                ('number_coins', models.FloatField()),
                ('profit', models.FloatField()),
                ('growth_factor', models.FloatField()),
                ('lambos', models.FloatField()),
                ('investment', models.FloatField()),
                ('symbol', models.CharField(db_index=True, max_length=100)),
                ('generation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'portfolio_results',
            },
        ),
        migrations.CreateModel(
            name='PortfolioLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('level', models.CharField(max_length=20)),
                ('generation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'portfolio_logs',
            },
        ),
        migrations.CreateModel(
            name='OpeningAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=100)),
                ('average', models.FloatField()),
                ('generation_date', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'opening_averages',
            },
        ),
        # Create indexes
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS opening_ave_symbol_519d97_idx ON opening_averages (symbol, generation_date);",
            reverse_sql="DROP INDEX IF EXISTS opening_ave_symbol_519d97_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS portfolio_l_symbol_a39722_idx ON portfolio_logs (symbol, generation_date);",
            reverse_sql="DROP INDEX IF EXISTS portfolio_l_symbol_a39722_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS portfolio_r_symbol_486ea4_idx ON portfolio_results (symbol, generation_date);",
            reverse_sql="DROP INDEX IF EXISTS portfolio_r_symbol_486ea4_idx;"
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS portfolio_r_query_b055c3_idx ON portfolio_results (query);",
            reverse_sql="DROP INDEX IF EXISTS portfolio_r_query_b055c3_idx;"
        ),
    ]
