# Generated by Django 4.0.2 on 2022-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LOGGING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SYMBOL', models.CharField(max_length=100)),
                ('INVESTMENT', models.FloatField()),
                ('GENERATIONDATE', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OPENING_AVERAGE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SYMBOL', models.CharField(max_length=100)),
                ('AVERAGE', models.FloatField()),
                ('GENERATIONDATE', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUERY', models.CharField(max_length=100)),
                ('NUMBERCOINS', models.FloatField()),
                ('PROFIT', models.FloatField()),
                ('GROWTHFACTOR', models.FloatField()),
                ('LAMBOS', models.FloatField()),
                ('INVESTMENT', models.FloatField()),
                ('SYMBOL', models.CharField(max_length=100)),
                ('GENERATIONDATE', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
